import * as fs from 'fs';
import * as path from 'path';
import { TextDecoder } from 'util';
import { promisify } from 'util';
import { parseGitignore } from './gitignoreParser';

const readFileAsync = promisify(fs.readFile);
const writeFileAsync = promisify(fs.writeFile);
const statAsync = promisify(fs.stat);
const readdirAsync = promisify(fs.readdir);

export interface DocumentOptions {
    outputPath: string;
    outputFormat: string;
    documentationType: string;
    includeItems?: string[];
    onProgress?: (message: string, percent: number) => void;
}

export class CodeCartographer {
    private rootDir: string;
    private processedFiles: Set<string> = new Set();
    private totalSize: number = 0;
    private fileCount: number = 0;
    private gitignoreMatcher: (filePath: string) => boolean;
    private progressCallback?: (message: string, percent: number) => void;
    private customIgnorePatterns: string[] = [];

    constructor(rootDir: string) {
        this.rootDir = rootDir;

        // Get custom ignore patterns from settings
        const config = require('vscode').workspace.getConfiguration('codeCartographer');
        this.customIgnorePatterns = config.get('ignorePatterns', [
            'node_modules', '.git', 'out', 'dist'
        ]);

        // Try to load .gitignore, but don't fail if it doesn't exist
        const gitignorePath = path.join(rootDir, '.gitignore');
        this.gitignoreMatcher = parseGitignore(gitignorePath);

        console.log(`CodeCartographer initialized for: ${rootDir}`);
        console.log(`Custom ignore patterns: ${this.customIgnorePatterns.join(', ')}`);
    }

    private shouldIgnore(filePath: string): boolean {
        const relativePath = path.relative(this.rootDir, filePath);

        // Log when ignoring files (for debugging)
        const shouldLog = false; // Set to true for verbose logging

        // Check gitignore rules
        if (this.gitignoreMatcher && this.gitignoreMatcher(filePath)) {
            if (shouldLog) { console.log(`Ignoring (gitignore): ${relativePath}`); }
            return true;
        }

        // Check ignored extensions
        const ignoredExtensions = ['.pyc', '.pyo', '.pyd', '.egg-info', '.o', '.obj', '.exe', '.dll'];
        if (ignoredExtensions.includes(path.extname(filePath))) {
            if (shouldLog) { console.log(`Ignoring (extension): ${relativePath}`); }
            return true;
        }

        // Check custom ignore patterns
        const parts = relativePath.split(path.sep);
        if (parts.some(part => this.customIgnorePatterns.includes(part))) {
            if (shouldLog) { console.log(`Ignoring (custom pattern): ${relativePath}`); }
            return true;
        }

        return false;
    }

    private async readFile(filePath: string): Promise<string | null> {
        try {
            // Check file size
            const stats = await statAsync(filePath);
            if (stats.size > 500000) {
                console.log(`Skipping large file: ${filePath}`);
                return null;
            }

            // Read file as buffer first
            const buffer = await readFileAsync(filePath);

            // Check if likely binary
            if (this.containsNullByte(buffer)) {
                console.log(`Skipping binary file: ${filePath}`);
                return null;
            }

            // Try different encodings
            const encodings = ['utf8', 'latin1', 'utf16le'];
            for (const encoding of encodings) {
                try {
                    const decoder = new TextDecoder(encoding);
                    const content = decoder.decode(buffer);
                    return content;
                } catch (err) {
                    continue;
                }
            }

            return null;
        } catch (err) {
            console.error(`Error reading file ${filePath}:`, err);
            return null;
        }
    }

    private containsNullByte(buffer: Buffer): boolean {
        // Check first 4KB for null bytes (common in binary files)
        const checkSize = Math.min(buffer.length, 4096);
        for (let i = 0; i < checkSize; i++) {
            if (buffer[i] === 0) {
                return true;
            }
        }
        return false;
    }

    private isLikelyGeneratedCode(content: string): boolean {
        const generatedMarkers = [
            "// Generated code",
            "/* Generated code",
            "@generated",
            "// GENERATED CODE - DO NOT MODIFY",
            "# Generated by",
            "// Auto-generated",
            "# This is a generated file",
        ];

        const firstLines = content.split('\n').slice(0, 5).join('\n');
        return generatedMarkers.some(marker =>
            firstLines.toLowerCase().includes(marker.toLowerCase())
        );
    }

    async processFile(filePath: string): Promise<any> {
        try {
            if (this.processedFiles.has(filePath) || this.shouldIgnore(filePath)) {
                return null;
            }

            this.processedFiles.add(filePath);

            const content = await this.readFile(filePath);
            if (!content) {
                return null;
            }

            if (this.isLikelyGeneratedCode(content)) {
                return null;
            }

            const stats = await statAsync(filePath);
            const fileSize = stats.size;
            this.totalSize += content.length;
            this.fileCount += 1;

            return {
                path: path.relative(this.rootDir, filePath),
                content: content,
                size: fileSize
            };
        } catch (err) {
            console.error(`Error processing ${filePath}:`, err);
            return null;
        }
    }

    private async getFileStructure(includeItems: string[] = []): Promise<any> {
        const structure = {
            name: path.basename(this.rootDir),
            type: 'directory',
            path: this.rootDir,
            children: []
        };

        // If no items specified, scan the entire directory
        let filesToProcess: string[] = [];
        if (includeItems.length === 0) {
            // Get all files in the directory recursively
            filesToProcess = await this.getAllFiles(this.rootDir);
            console.log(`Found ${filesToProcess.length} total files to process`);
        } else {
            filesToProcess = includeItems;
            console.log(`Using ${filesToProcess.length} provided files to process`);
        }

        // Filter out ignored files
        const filteredFiles = filesToProcess.filter(file => !this.shouldIgnore(file));
        console.log(`After filtering, ${filteredFiles.length} files remain`);

        // Add all files to the structure
        for (const fullPath of filteredFiles) {
            const relativePath = path.relative(this.rootDir, fullPath);
            this.addPathToStructure(structure, fullPath, relativePath);
        }

        return structure;
    }

    private addPathToStructure(
        structure: any,
        fullPath: string,
        relativePath: string
    ): void {
        const parts = relativePath.split(path.sep);
        let current = structure;

        for (let i = 0; i < parts.length; i++) {
            const part = parts[i];
            if (!part) { continue; } // Skip empty parts

            const isLast = i === parts.length - 1;
            const isFile = isLast && fs.statSync(fullPath).isFile();
            const currentRelativePath = parts.slice(0, i + 1).join(path.sep);
            const currentFullPath = path.join(this.rootDir, currentRelativePath);

            // Find existing node or create new one
            let node = current.children.find((child: any) => child.name === part);

            if (!node) {
                node = {
                    name: part,
                    type: isFile ? 'file' : 'directory',
                    path: currentFullPath
                };

                if (!isFile) {
                    node.children = [];
                } else {
                    try {
                        const stats = fs.statSync(fullPath);
                        node.size = stats.size;
                    } catch (error) {
                        console.error(`Error getting stats for ${fullPath}:`, error);
                        node.size = 0;
                    }
                }

                current.children.push(node);
            }

            if (!isFile) {
                current = node;
            }
        }
    }

    private async getAllFiles(dir: string): Promise<string[]> {
        try {
            const entries = await readdirAsync(dir, { withFileTypes: true });

            const promises = entries.map(async entry => {
                const fullPath = path.join(dir, entry.name);

                // Skip ignored directories early for performance
                if (entry.isDirectory() && this.customIgnorePatterns.includes(entry.name)) {
                    return [];
                }

                if (entry.isDirectory()) {
                    return this.getAllFiles(fullPath);
                } else {
                    return [fullPath];
                }
            });

            const results = await Promise.all(promises);
            return results.flat();
        } catch (error) {
            console.error(`Error reading directory ${dir}:`, error);
            return [];
        }
    }

    async document(options: DocumentOptions): Promise<void> {
        const {
            outputPath,
            outputFormat = 'json',
            documentationType = 'both',
            includeItems = [],
            onProgress = undefined
        } = options;

        this.progressCallback = onProgress;
        this.reportProgress('Starting documentation process...', 0);

        let fileStructure = null;
        let fileContents = [];

        // Generate file structure if needed
        if (documentationType === 'structure' || documentationType === 'both') {
            this.reportProgress('Analyzing file structure...', 10);

            const items = includeItems.length > 0 ?
                includeItems.map(item => path.resolve(this.rootDir, item)) :
                [];

            fileStructure = await this.getFileStructure(items);
            console.log(`Structure generated with ${fileStructure.children.length} top-level items`);
        }

        // Generate file documentation if needed
        if (documentationType === 'documentation' || documentationType === 'both') {
            this.reportProgress('Processing files...', 30);

            const filesToProcess = includeItems.length > 0 ?
                includeItems.map(item => path.resolve(this.rootDir, item)) :
                await this.getAllFiles(this.rootDir);

            console.log(`Generating documentation for ${filesToProcess.length} files`);

            let processed = 0;
            for (const filePath of filesToProcess) {
                const result = await this.processFile(filePath);
                if (result) {
                    fileContents.push(result);
                }

                processed++;
                if (processed % 10 === 0 || processed === filesToProcess.length) {
                    const percent = Math.floor(30 + (processed / filesToProcess.length) * 50);
                    this.reportProgress(`Processed ${processed}/${filesToProcess.length} files...`, percent);
                }
            }

            console.log(`Successfully documented ${fileContents.length} files`);
        }

        // Generate output
        this.reportProgress('Generating output...', 90);

        const outputData = {
            project_info: {
                path: this.rootDir,
                generated_on: new Date().toISOString().replace('T', ' ').substr(0, 19),
                documentation_type: documentationType,
                total_files: this.fileCount,
                total_size: this.totalSize
            },
            file_structure: fileStructure,
            files: fileContents
        };

        // Write output in specified format
        try {
            switch (outputFormat) {
                case 'json':
                    await writeFileAsync(outputPath, JSON.stringify(outputData, null, 2), 'utf8');
                    break;
                case 'txt':
                    await this.writeTxtOutput(outputPath, outputData);
                    break;
                case 'csv':
                    await this.writeCsvOutput(outputPath, outputData);
                    break;
                default:
                    await writeFileAsync(outputPath, JSON.stringify(outputData, null, 2), 'utf8');
            }
            console.log(`Documentation written to ${outputPath}`);
        } catch (error) {
            console.error(`Error writing documentation:`, error);
            throw error;
        }

        this.reportProgress('Documentation completed!', 100);
    }

    private async writeTxtOutput(outputPath: string, data: any): Promise<void> {
        let output = `Project Documentation\n`;
        output += `${'='.repeat(80)}\n`;
        output += `Project Path: ${data.project_info.path}\n`;
        output += `Generated on: ${data.project_info.generated_on}\n`;
        output += `${'='.repeat(80)}\n\n`;

        if (data.file_structure) {
            output += `\nFile Structure:\n`;
            output += `${'='.repeat(80)}\n`;
            output += this.formatStructureAsTxt(data.file_structure);
            output += `\n${'-'.repeat(80)}\n`;
        }

        if (data.files && data.files.length > 0) {
            output += `\nFile Contents:\n`;
            output += `${'='.repeat(80)}\n`;

            for (const file of data.files) {
                output += `\n## File: ${file.path}\n`;
                output += `Size: ${Math.round(file.size / 1024 * 100) / 100} KB\n`;
                output += `${'='.repeat(80)}\n\n`;
                output += file.content;
                output += `\n\n`;
            }
        }

        await writeFileAsync(outputPath, output, 'utf8');
    }

    private formatStructureAsTxt(structure: any, prefix = ''): string {
        let output = `${prefix}${structure.name}\n`;

        if (structure.children) {
            // Sort directories first, then files alphabetically
            const sortedChildren = [...structure.children].sort((a, b) => {
                if (a.type !== b.type) {
                    return a.type === 'directory' ? -1 : 1;
                }
                return a.name.localeCompare(b.name);
            });

            for (let i = 0; i < sortedChildren.length; i++) {
                const isLast = i === sortedChildren.length - 1;
                const childPrefix = prefix + (isLast ? '└── ' : '├── ');
                const grandchildPrefix = prefix + (isLast ? '    ' : '│   ');

                output += this.formatStructureAsTxt(sortedChildren[i], childPrefix);
            }
        }

        return output;
    }

    private async writeCsvOutput(outputPath: string, data: any): Promise<void> {
        let output = '';

        // Add structure if available
        if (data.file_structure) {
            output += 'type,name,path,size\n';
            output += this.formatStructureAsCsv(data.file_structure);
        }

        // Add content if available
        if (data.files && data.files.length > 0) {
            if (output) {
                output += '\n\n';
            }

            output += 'path,size\n';

            for (const file of data.files) {
                output += `"${file.path}",${file.size}\n`;
            }
        }

        await writeFileAsync(outputPath, output, 'utf8');
    }

    private formatStructureAsCsv(structure: any, parentPath = ''): string {
        const currentPath = parentPath ?
            `${parentPath}/${structure.name}` :
            structure.name;

        let output = `${structure.type},${structure.name},${currentPath},${structure.size || ''}\n`;

        if (structure.children) {
            for (const child of structure.children) {
                output += this.formatStructureAsCsv(child, currentPath);
            }
        }

        return output;
    }

    private reportProgress(message: string, percent: number): void {
        if (this.progressCallback) {
            this.progressCallback(message, percent);
        }
    }
}