import * as fs from 'fs';
import * as path from 'path';
import { TextDecoder } from 'util';
import { promisify } from 'util';
import { getLogger } from './logger';

const readFileAsync = promisify(fs.readFile);
const statAsync = promisify(fs.stat);

export interface FileProcessingOptions {
    maxSize: number;
    skipBinary: boolean;
    skipGenerated: boolean;
    onProgress?: (filePath: string, bytesRead: number) => void;
}

export class FileProcessor {
    private static readonly BINARY_CHECK_SIZE = 8192; // Check first 8KB for binary detection
    private static readonly DEFAULT_ENCODING_ATTEMPTS = ['utf8', 'latin1', 'utf16le', 'ascii'];
    private static readonly GENERATED_FILE_MARKERS = [
        "// Generated code",
        "/* Generated code",
        "@generated",
        "// GENERATED CODE - DO NOT MODIFY",
        "# Generated by",
        "// Auto-generated",
        "# This is a generated file",
        "DO NOT EDIT",
        "/* eslint-disable */", // Often used in generated files
        "// ------------------" // Common in generated separator
    ];

    private logger = getLogger();

    constructor() { }

    /**
     * Process a file and extract its content with proper encoding detection
     */
    public async processFile(filePath: string, options: FileProcessingOptions): Promise<{ content: string; size: number } | null> {
        try {
            this.logger.debug(`Processing file: ${filePath}`);

            // Check file exists
            if (!fs.existsSync(filePath)) {
                this.logger.warn(`File does not exist: ${filePath}`);
                return null;
            }

            // Check file stats
            const stats = await statAsync(filePath);

            // Skip if not a regular file
            if (!stats.isFile()) {
                this.logger.debug(`Not a regular file: ${filePath}`);
                return null;
            }

            // Check file size
            if (stats.size > options.maxSize) {
                this.logger.info(`Skipping large file (${stats.size} bytes): ${filePath}`);
                return null;
            }

            // Read file as buffer
            const buffer = await readFileAsync(filePath);

            // Skip binary files if specified
            if (options.skipBinary && this.isBinaryFile(buffer)) {
                this.logger.info(`Skipping binary file: ${filePath}`);
                return null;
            }

            // Try to decode the content
            const content = await this.decodeFileContent(buffer, filePath);
            if (!content) {
                this.logger.warn(`Could not decode file content: ${filePath}`);
                return null;
            }

            // Skip generated files if specified
            if (options.skipGenerated && this.isGeneratedFile(content)) {
                this.logger.info(`Skipping generated file: ${filePath}`);
                return null;
            }

            // Call progress callback if provided
            if (options.onProgress) {
                options.onProgress(filePath, stats.size);
            }

            return { content, size: stats.size };
        } catch (error) {
            this.logger.error(`Error processing file ${filePath}:`, error);
            return null;
        }
    }

    /**
     * Check if a file is likely a binary file
     */
    private isBinaryFile(buffer: Buffer): boolean {
        // Strategy: Check for null bytes and unusual character distributions

        const checkSize = Math.min(buffer.length, FileProcessor.BINARY_CHECK_SIZE);

        // Check for null bytes (common in binary files)
        for (let i = 0; i < checkSize; i++) {
            if (buffer[i] === 0) {
                return true;
            }
        }

        // Count control characters (besides common whitespace)
        // High percentage of control chars suggests binary
        let controlCharCount = 0;
        for (let i = 0; i < checkSize; i++) {
            const byte = buffer[i];
            // Skip common whitespace ASCII: 9 (tab), 10 (LF), 13 (CR)
            if ((byte < 32 && byte !== 9 && byte !== 10 && byte !== 13) || byte === 127) {
                controlCharCount++;
            }
        }

        // If more than 10% of the checked content is control characters, likely binary
        if (controlCharCount > checkSize * 0.1) {
            return true;
        }

        return false;
    }

    /**
     * Try multiple encodings to decode file content
     */
    private async decodeFileContent(buffer: Buffer, filePath: string): Promise<string | null> {
        // Try to detect encoding from file content
        let encodingsToTry = [...FileProcessor.DEFAULT_ENCODING_ATTEMPTS];

        // Adjust encoding priority based on file extension
        const ext = path.extname(filePath).toLowerCase();
        if (['.js', '.ts', '.json', '.html', '.css', '.md'].includes(ext)) {
            // These are almost certainly UTF-8
            encodingsToTry = ['utf8', ...encodingsToTry.filter(e => e !== 'utf8')];
        }

        // Try each encoding
        for (const encoding of encodingsToTry) {
            try {
                const decoder = new TextDecoder(encoding);
                const content = decoder.decode(buffer);

                // Validate that encoding worked (look for replacement chars)
                if (!content.includes('�')) {
                    this.logger.debug(`Successfully decoded ${filePath} with ${encoding} encoding`);
                    return content;
                }
            } catch (err) {
                this.logger.debug(`Failed to decode ${filePath} with ${encoding} encoding`);
                continue;
            }
        }

        // If we've tried all encodings and none worked well, use UTF-8 as last resort
        try {
            const content = buffer.toString('utf8');
            this.logger.warn(`Used fallback UTF-8 encoding for ${filePath} (may have encoding issues)`);
            return content;
        } catch (err) {
            this.logger.error(`All encoding attempts failed for ${filePath}`);
            return null;
        }
    }

    /**
     * Check if a file is likely generated code
     */
    private isGeneratedFile(content: string): boolean {
        // Look for generated code markers in first few lines
        const firstFewLines = content.split('\n').slice(0, 10).join('\n').toLowerCase();

        return FileProcessor.GENERATED_FILE_MARKERS.some(marker =>
            firstFewLines.includes(marker.toLowerCase())
        );
    }

    /**
     * Extract file metadata without full content
     */
    public async getFileMetadata(filePath: string): Promise<{ path: string; size: number; type: string } | null> {
        try {
            if (!fs.existsSync(filePath)) {
                return null;
            }

            const stats = await statAsync(filePath);
            if (!stats.isFile()) {
                return null;
            }

            return {
                path: filePath,
                size: stats.size,
                type: this.detectFileType(filePath)
            };
        } catch (error) {
            this.logger.error(`Error getting file metadata for ${filePath}:`, error);
            return null;
        }
    }

    /**
     * Detect file type based on extension
     */
    private detectFileType(filePath: string): string {
        const ext = path.extname(filePath).toLowerCase();

        // Common file type mapping
        const fileTypeMap: Record<string, string> = {
            '.js': 'JavaScript',
            '.ts': 'TypeScript',
            '.jsx': 'React JSX',
            '.tsx': 'React TSX',
            '.html': 'HTML',
            '.css': 'CSS',
            '.scss': 'SCSS',
            '.sass': 'Sass',
            '.less': 'Less',
            '.json': 'JSON',
            '.md': 'Markdown',
            '.py': 'Python',
            '.java': 'Java',
            '.rb': 'Ruby',
            '.php': 'PHP',
            '.c': 'C',
            '.cpp': 'C++',
            '.h': 'C/C++ Header',
            '.cs': 'C#',
            '.go': 'Go',
            '.rs': 'Rust',
            '.swift': 'Swift',
            '.kt': 'Kotlin',
            '.sh': 'Shell Script',
            '.bat': 'Batch Script',
            '.ps1': 'PowerShell',
            '.xml': 'XML',
            '.yaml': 'YAML',
            '.yml': 'YAML',
            '.toml': 'TOML',
            '.sql': 'SQL',
            '.graphql': 'GraphQL',
            '.txt': 'Text',
            '.csv': 'CSV',
            '.svg': 'SVG',
            '.png': 'PNG Image',
            '.jpg': 'JPEG Image',
            '.jpeg': 'JPEG Image',
            '.gif': 'GIF Image',
            '.pdf': 'PDF Document'
        };

        return fileTypeMap[ext] || 'Unknown';
    }
}